import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case zhHans
    case en

    var id: String { rawValue }

    var title: String {
        switch self {
        case .zhHans: "中文"
        case .en: "English"
        }
    }
}

enum AppL10n {
    static func text(_ key: String, language: AppLanguage) -> String {
        switch language {
        case .zhHans:
            zhHans[key] ?? key
        case .en:
            en[key] ?? zhHans[key] ?? key
        }
    }

    private static let zhHans: [String: String] = [
        "home": "首页",
        "following": "关注",
        "me": "我",
        "settings": "设置",
        "profile": "个人资料",
        "name": "名称",
        "appearance": "外观",
        "language": "语言",
        "automatic": "自动",
        "day": "日间",
        "night": "夜间",
        "wallhaven_account": "Wallhaven 账号",
        "api_key": "API Key",
        "username": "用户名",
        "online": "在线",
        "offline": "离线",
        "restricted_content": "限制级内容",
        "restricted_description": "开启后包含微敏感与限制级内容，需要有效 API Key，并取决于 Wallhaven 账号设置。",
        "download_folder": "下载目录",
        "choose": "选择",
        "open_folder": "打开目录",
        "cache": "缓存",
        "clear_cache": "清除缓存",
        "cache_cleared": "缓存已清除",
        "software_version": "软件版本",
        "download_queue": "下载队列",
        "close": "关闭",
        "retry": "重试",
        "retry_failed": "重试失败",
        "clear": "清理",
        "no_download_tasks": "没有下载任务",
        "queued": "等待下载",
        "downloading_original": "正在下载原图",
        "downloaded": "已下载",
        "download_failed": "下载失败",
        "download_original": "下载原图",
        "download_selected": "下载 %@ 张",
        "latest": "最新",
        "popular": "热门",
        "random": "随机",
        "orientation": "方向",
        "feed_mode": "浏览模式",
        "landscape_wallpapers": "横屏壁纸",
        "portrait_wallpapers": "竖屏壁纸",
        "no_network": "无网络",
        "network_unavailable_message": "无网络或代理不可用，请检查网络或代理后刷新。",
        "no_wallpapers": "没有壁纸",
        "empty_keyword_result": "这个关键词暂时没有结果。",
        "wallhaven_empty_help": "Wallhaven 没有返回图片，请确认网络可以访问 wallhaven.cc。",
        "at_least_one_category": "至少需要一个内容分类。",
        "at_least_one_purity": "至少需要一个内容分级。",
        "reload": "重新加载",
        "loading": "正在加载",
        "refreshing": "正在刷新",
        "refresh_complete": "已刷新 %@ 张",
        "refresh_failed": "刷新失败",
        "continue_load_more": "继续下滑加载更多",
        "select_all": "全选已加载",
        "clear_selection": "清空",
        "done": "完成",
        "your_subscriptions": "你的订阅",
        "subscription_empty": "订阅用户或关注标签后，更新会出现在这里",
        "subscribed_users": "订阅用户",
        "followed_tags": "关注标签",
        "subscribe": "订阅",
        "subscribed": "已订阅",
        "follow": "关注",
        "followed": "已关注",
        "tags": "标签",
        "uploads": "上传",
        "favorites": "收藏",
        "profile_comments": "留言",
        "no_uploads": "没有上传",
        "no_favorites": "没有收藏",
        "no_profile_comments": "暂无公开留言",
        "joined": "加入时间",
        "joined_year_format": "%@年",
        "subscribers": "订阅者",
        "publish": "发布",
        "post_comment": "发表留言",
        "profile_data_unavailable": "暂时无法读取 Wallhaven 主页资料",
        "open_in_browser": "在浏览器打开",
        "copy_link": "复制链接",
        "information": "信息",
        "resolution": "分辨率",
        "ratio": "比例",
        "size": "大小",
        "type": "类型",
        "views": "浏览",
        "uploader": "上传者",
        "wallpaper_count": "%@ 张",
        "menu": "筛选",
        "back": "返回",
        "forward": "前进",
        "refresh": "刷新",
        "import_local": "导入本地图片",
        "sync_profile": "同步 Wallhaven 资料",
        "save_automatically": "修改会自动保存"
    ]

    private static let en: [String: String] = [
        "home": "Home",
        "following": "Following",
        "me": "Me",
        "settings": "Settings",
        "profile": "Profile",
        "name": "Name",
        "appearance": "Appearance",
        "language": "Language",
        "automatic": "Auto",
        "day": "Light",
        "night": "Dark",
        "wallhaven_account": "Wallhaven Account",
        "api_key": "API Key",
        "username": "Username",
        "online": "Online",
        "offline": "Offline",
        "restricted_content": "Restricted Content",
        "restricted_description": "Includes sketchy and restricted content. A valid API Key is required and Wallhaven account settings still apply.",
        "download_folder": "Download Folder",
        "choose": "Choose",
        "open_folder": "Open Folder",
        "cache": "Cache",
        "clear_cache": "Clear Cache",
        "cache_cleared": "Cache cleared",
        "software_version": "Version",
        "download_queue": "Downloads",
        "close": "Close",
        "retry": "Retry",
        "retry_failed": "Retry Failed",
        "clear": "Clear",
        "no_download_tasks": "No downloads",
        "queued": "Queued",
        "downloading_original": "Downloading original",
        "downloaded": "Downloaded",
        "download_failed": "Download failed",
        "download_original": "Download Original",
        "download_selected": "Download %@",
        "latest": "Latest",
        "popular": "Popular",
        "random": "Random",
        "orientation": "Orientation",
        "feed_mode": "Feed Mode",
        "landscape_wallpapers": "Landscape",
        "portrait_wallpapers": "Portrait",
        "no_network": "No Network",
        "network_unavailable_message": "No network or proxy is available. Check the connection and refresh.",
        "no_wallpapers": "No Wallpapers",
        "empty_keyword_result": "No results for this keyword yet.",
        "wallhaven_empty_help": "Wallhaven returned no images. Check whether wallhaven.cc is reachable.",
        "at_least_one_category": "Select at least one category.",
        "at_least_one_purity": "Select at least one content rating.",
        "reload": "Reload",
        "loading": "Loading",
        "refreshing": "Refreshing",
        "refresh_complete": "Refreshed %@",
        "refresh_failed": "Refresh Failed",
        "continue_load_more": "Scroll for more",
        "select_all": "Select Loaded",
        "clear_selection": "Clear",
        "done": "Done",
        "your_subscriptions": "Your Subscriptions",
        "subscription_empty": "Follow users or tags to see updates here",
        "subscribed_users": "Users",
        "followed_tags": "Tags",
        "subscribe": "Subscribe",
        "subscribed": "Subscribed",
        "follow": "Follow",
        "followed": "Followed",
        "tags": "Tags",
        "uploads": "Uploads",
        "favorites": "Favorites",
        "profile_comments": "Comments",
        "no_uploads": "No Uploads",
        "no_favorites": "No Favorites",
        "no_profile_comments": "No public comments",
        "joined": "Joined",
        "joined_year_format": "%@",
        "subscribers": "Subscribers",
        "publish": "Publish",
        "post_comment": "Post Comment",
        "profile_data_unavailable": "Wallhaven profile data is temporarily unavailable",
        "open_in_browser": "Open in Browser",
        "copy_link": "Copy Link",
        "information": "Information",
        "resolution": "Resolution",
        "ratio": "Ratio",
        "size": "Size",
        "type": "Type",
        "views": "Views",
        "uploader": "Uploader",
        "wallpaper_count": "%@",
        "menu": "Filters",
        "back": "Back",
        "forward": "Forward",
        "refresh": "Refresh",
        "import_local": "Import Local Images",
        "sync_profile": "Sync Wallhaven Profile",
        "save_automatically": "Changes save automatically"
    ]
}
